fix: Missing required module `SwiftCompilerPlugin` in `CasePathableMacroTests`
This fixes an error when running `swift build`:
```
Tests/CasePathsMacrosTests/CasePathableMacroTests.swift:2:10: error: missing required module 'SwiftCompilerPlugin'
```
when importing CasePathsMacros.

This one is strange, I'm not sure why SwiftCompilerPlugin isn't being transitively imported through CasePathsMacros.